stages:
  - build
  - deploy

build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [ "" ]
  stage: build
  before_script:
    - mkdir -p /kaniko/.docker
    - |
      cat <<- EOF > /kaniko/.docker/config.json
      {
        "auths": {
          "${CI_REGISTRY}": {
            "auth": "$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')"
          }
        }
      }
      EOF
  script:
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --skip-unused-stages
      --destination "${CI_REGISTRY_IMAGE}:${OPENSEEFACE_VERSION}"
      --destination "${CI_REGISTRY_IMAGE}:latest"
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
